// Agent: Agent Mode, Date: 2025-08-16, Observation: Public C API header for libasyncinput MVP
#ifndef ASYNCINPUT_H
#define ASYNCINPUT_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Zero-cost cross-platform event constants
 * On Linux, these map directly to evdev's input-event-codes.h values.
 * On other platforms, values are defined to stable integers maintained by this library.
 */
#ifdef __linux__
#  include <linux/input-event-codes.h>
#define NI_INPUT_PROP_POINTER INPUT_PROP_POINTER
#define NI_INPUT_PROP_DIRECT INPUT_PROP_DIRECT
#define NI_INPUT_PROP_BUTTONPAD INPUT_PROP_BUTTONPAD
#define NI_INPUT_PROP_SEMI_MT INPUT_PROP_SEMI_MT
#define NI_INPUT_PROP_TOPBUTTONPAD INPUT_PROP_TOPBUTTONPAD
#define NI_INPUT_PROP_POINTING_STICK INPUT_PROP_POINTING_STICK
#define NI_INPUT_PROP_ACCELEROMETER INPUT_PROP_ACCELEROMETER
#define NI_INPUT_PROP_MAX INPUT_PROP_MAX
#define NI_INPUT_PROP_CNT INPUT_PROP_CNT
#define NI_EV_SYN EV_SYN
#define NI_EV_KEY EV_KEY
#define NI_EV_REL EV_REL
#define NI_EV_ABS EV_ABS
#define NI_EV_MSC EV_MSC
#define NI_EV_SW EV_SW
#define NI_EV_LED EV_LED
#define NI_EV_SND EV_SND
#define NI_EV_REP EV_REP
#define NI_EV_FF EV_FF
#define NI_EV_PWR EV_PWR
#define NI_EV_FF_STATUS EV_FF_STATUS
#define NI_EV_MAX EV_MAX
#define NI_EV_CNT EV_CNT
#define NI_SYN_REPORT SYN_REPORT
#define NI_SYN_CONFIG SYN_CONFIG
#define NI_SYN_MT_REPORT SYN_MT_REPORT
#define NI_SYN_DROPPED SYN_DROPPED
#define NI_SYN_MAX SYN_MAX
#define NI_SYN_CNT SYN_CNT
#define NI_KEY_RESERVED KEY_RESERVED
#define NI_KEY_ESC KEY_ESC
#define NI_KEY_1 KEY_1
#define NI_KEY_2 KEY_2
#define NI_KEY_3 KEY_3
#define NI_KEY_4 KEY_4
#define NI_KEY_5 KEY_5
#define NI_KEY_6 KEY_6
#define NI_KEY_7 KEY_7
#define NI_KEY_8 KEY_8
#define NI_KEY_9 KEY_9
#define NI_KEY_0 KEY_0
#define NI_KEY_MINUS KEY_MINUS
#define NI_KEY_EQUAL KEY_EQUAL
#define NI_KEY_BACKSPACE KEY_BACKSPACE
#define NI_KEY_TAB KEY_TAB
#define NI_KEY_Q KEY_Q
#define NI_KEY_W KEY_W
#define NI_KEY_E KEY_E
#define NI_KEY_R KEY_R
#define NI_KEY_T KEY_T
#define NI_KEY_Y KEY_Y
#define NI_KEY_U KEY_U
#define NI_KEY_I KEY_I
#define NI_KEY_O KEY_O
#define NI_KEY_P KEY_P
#define NI_KEY_LEFTBRACE KEY_LEFTBRACE
#define NI_KEY_RIGHTBRACE KEY_RIGHTBRACE
#define NI_KEY_ENTER KEY_ENTER
#define NI_KEY_LEFTCTRL KEY_LEFTCTRL
#define NI_KEY_A KEY_A
#define NI_KEY_S KEY_S
#define NI_KEY_D KEY_D
#define NI_KEY_F KEY_F
#define NI_KEY_G KEY_G
#define NI_KEY_H KEY_H
#define NI_KEY_J KEY_J
#define NI_KEY_K KEY_K
#define NI_KEY_L KEY_L
#define NI_KEY_SEMICOLON KEY_SEMICOLON
#define NI_KEY_APOSTROPHE KEY_APOSTROPHE
#define NI_KEY_GRAVE KEY_GRAVE
#define NI_KEY_LEFTSHIFT KEY_LEFTSHIFT
#define NI_KEY_BACKSLASH KEY_BACKSLASH
#define NI_KEY_Z KEY_Z
#define NI_KEY_X KEY_X
#define NI_KEY_C KEY_C
#define NI_KEY_V KEY_V
#define NI_KEY_B KEY_B
#define NI_KEY_N KEY_N
#define NI_KEY_M KEY_M
#define NI_KEY_COMMA KEY_COMMA
#define NI_KEY_DOT KEY_DOT
#define NI_KEY_SLASH KEY_SLASH
#define NI_KEY_RIGHTSHIFT KEY_RIGHTSHIFT
#define NI_KEY_KPASTERISK KEY_KPASTERISK
#define NI_KEY_LEFTALT KEY_LEFTALT
#define NI_KEY_SPACE KEY_SPACE
#define NI_KEY_CAPSLOCK KEY_CAPSLOCK
#define NI_KEY_F1 KEY_F1
#define NI_KEY_F2 KEY_F2
#define NI_KEY_F3 KEY_F3
#define NI_KEY_F4 KEY_F4
#define NI_KEY_F5 KEY_F5
#define NI_KEY_F6 KEY_F6
#define NI_KEY_F7 KEY_F7
#define NI_KEY_F8 KEY_F8
#define NI_KEY_F9 KEY_F9
#define NI_KEY_F10 KEY_F10
#define NI_KEY_NUMLOCK KEY_NUMLOCK
#define NI_KEY_SCROLLLOCK KEY_SCROLLLOCK
#define NI_KEY_KP7 KEY_KP7
#define NI_KEY_KP8 KEY_KP8
#define NI_KEY_KP9 KEY_KP9
#define NI_KEY_KPMINUS KEY_KPMINUS
#define NI_KEY_KP4 KEY_KP4
#define NI_KEY_KP5 KEY_KP5
#define NI_KEY_KP6 KEY_KP6
#define NI_KEY_KPPLUS KEY_KPPLUS
#define NI_KEY_KP1 KEY_KP1
#define NI_KEY_KP2 KEY_KP2
#define NI_KEY_KP3 KEY_KP3
#define NI_KEY_KP0 KEY_KP0
#define NI_KEY_KPDOT KEY_KPDOT
#define NI_KEY_ZENKAKUHANKAKU KEY_ZENKAKUHANKAKU
#define NI_KEY_102ND KEY_102ND
#define NI_KEY_F11 KEY_F11
#define NI_KEY_F12 KEY_F12
#define NI_KEY_RO KEY_RO
#define NI_KEY_KATAKANA KEY_KATAKANA
#define NI_KEY_HIRAGANA KEY_HIRAGANA
#define NI_KEY_HENKAN KEY_HENKAN
#define NI_KEY_KATAKANAHIRAGANA KEY_KATAKANAHIRAGANA
#define NI_KEY_MUHENKAN KEY_MUHENKAN
#define NI_KEY_KPJPCOMMA KEY_KPJPCOMMA
#define NI_KEY_KPENTER KEY_KPENTER
#define NI_KEY_RIGHTCTRL KEY_RIGHTCTRL
#define NI_KEY_KPSLASH KEY_KPSLASH
#define NI_KEY_SYSRQ KEY_SYSRQ
#define NI_KEY_RIGHTALT KEY_RIGHTALT
#define NI_KEY_LINEFEED KEY_LINEFEED
#define NI_KEY_HOME KEY_HOME
#define NI_KEY_UP KEY_UP
#define NI_KEY_PAGEUP KEY_PAGEUP
#define NI_KEY_LEFT KEY_LEFT
#define NI_KEY_RIGHT KEY_RIGHT
#define NI_KEY_END KEY_END
#define NI_KEY_DOWN KEY_DOWN
#define NI_KEY_PAGEDOWN KEY_PAGEDOWN
#define NI_KEY_INSERT KEY_INSERT
#define NI_KEY_DELETE KEY_DELETE
#define NI_KEY_MACRO KEY_MACRO
#define NI_KEY_MUTE KEY_MUTE
#define NI_KEY_VOLUMEDOWN KEY_VOLUMEDOWN
#define NI_KEY_VOLUMEUP KEY_VOLUMEUP
#define NI_KEY_POWER KEY_POWER
#define NI_KEY_KPEQUAL KEY_KPEQUAL
#define NI_KEY_KPPLUSMINUS KEY_KPPLUSMINUS
#define NI_KEY_PAUSE KEY_PAUSE
#define NI_KEY_SCALE KEY_SCALE
#define NI_KEY_KPCOMMA KEY_KPCOMMA
#define NI_KEY_HANGEUL KEY_HANGEUL
#define NI_KEY_HANGUEL KEY_HANGUEL
#define NI_KEY_HANJA KEY_HANJA
#define NI_KEY_YEN KEY_YEN
#define NI_KEY_LEFTMETA KEY_LEFTMETA
#define NI_KEY_RIGHTMETA KEY_RIGHTMETA
#define NI_KEY_COMPOSE KEY_COMPOSE
#define NI_KEY_STOP KEY_STOP
#define NI_KEY_AGAIN KEY_AGAIN
#define NI_KEY_PROPS KEY_PROPS
#define NI_KEY_UNDO KEY_UNDO
#define NI_KEY_FRONT KEY_FRONT
#define NI_KEY_COPY KEY_COPY
#define NI_KEY_OPEN KEY_OPEN
#define NI_KEY_PASTE KEY_PASTE
#define NI_KEY_FIND KEY_FIND
#define NI_KEY_CUT KEY_CUT
#define NI_KEY_HELP KEY_HELP
#define NI_KEY_MENU KEY_MENU
#define NI_KEY_CALC KEY_CALC
#define NI_KEY_SETUP KEY_SETUP
#define NI_KEY_SLEEP KEY_SLEEP
#define NI_KEY_WAKEUP KEY_WAKEUP
#define NI_KEY_FILE KEY_FILE
#define NI_KEY_SENDFILE KEY_SENDFILE
#define NI_KEY_DELETEFILE KEY_DELETEFILE
#define NI_KEY_XFER KEY_XFER
#define NI_KEY_PROG1 KEY_PROG1
#define NI_KEY_PROG2 KEY_PROG2
#define NI_KEY_WWW KEY_WWW
#define NI_KEY_MSDOS KEY_MSDOS
#define NI_KEY_COFFEE KEY_COFFEE
#define NI_KEY_SCREENLOCK KEY_SCREENLOCK
#define NI_KEY_ROTATE_DISPLAY KEY_ROTATE_DISPLAY
#define NI_KEY_DIRECTION KEY_DIRECTION
#define NI_KEY_CYCLEWINDOWS KEY_CYCLEWINDOWS
#define NI_KEY_MAIL KEY_MAIL
#define NI_KEY_BOOKMARKS KEY_BOOKMARKS
#define NI_KEY_COMPUTER KEY_COMPUTER
#define NI_KEY_BACK KEY_BACK
#define NI_KEY_FORWARD KEY_FORWARD
#define NI_KEY_CLOSECD KEY_CLOSECD
#define NI_KEY_EJECTCD KEY_EJECTCD
#define NI_KEY_EJECTCLOSECD KEY_EJECTCLOSECD
#define NI_KEY_NEXTSONG KEY_NEXTSONG
#define NI_KEY_PLAYPAUSE KEY_PLAYPAUSE
#define NI_KEY_PREVIOUSSONG KEY_PREVIOUSSONG
#define NI_KEY_STOPCD KEY_STOPCD
#define NI_KEY_RECORD KEY_RECORD
#define NI_KEY_REWIND KEY_REWIND
#define NI_KEY_PHONE KEY_PHONE
#define NI_KEY_ISO KEY_ISO
#define NI_KEY_CONFIG KEY_CONFIG
#define NI_KEY_HOMEPAGE KEY_HOMEPAGE
#define NI_KEY_REFRESH KEY_REFRESH
#define NI_KEY_EXIT KEY_EXIT
#define NI_KEY_MOVE KEY_MOVE
#define NI_KEY_EDIT KEY_EDIT
#define NI_KEY_SCROLLUP KEY_SCROLLUP
#define NI_KEY_SCROLLDOWN KEY_SCROLLDOWN
#define NI_KEY_KPLEFTPAREN KEY_KPLEFTPAREN
#define NI_KEY_KPRIGHTPAREN KEY_KPRIGHTPAREN
#define NI_KEY_NEW KEY_NEW
#define NI_KEY_REDO KEY_REDO
#define NI_KEY_F13 KEY_F13
#define NI_KEY_F14 KEY_F14
#define NI_KEY_F15 KEY_F15
#define NI_KEY_F16 KEY_F16
#define NI_KEY_F17 KEY_F17
#define NI_KEY_F18 KEY_F18
#define NI_KEY_F19 KEY_F19
#define NI_KEY_F20 KEY_F20
#define NI_KEY_F21 KEY_F21
#define NI_KEY_F22 KEY_F22
#define NI_KEY_F23 KEY_F23
#define NI_KEY_F24 KEY_F24
#define NI_KEY_PLAYCD KEY_PLAYCD
#define NI_KEY_PAUSECD KEY_PAUSECD
#define NI_KEY_PROG3 KEY_PROG3
#define NI_KEY_PROG4 KEY_PROG4
#define NI_KEY_ALL_APPLICATIONS KEY_ALL_APPLICATIONS
#define NI_KEY_DASHBOARD KEY_DASHBOARD
#define NI_KEY_SUSPEND KEY_SUSPEND
#define NI_KEY_CLOSE KEY_CLOSE
#define NI_KEY_PLAY KEY_PLAY
#define NI_KEY_FASTFORWARD KEY_FASTFORWARD
#define NI_KEY_BASSBOOST KEY_BASSBOOST
#define NI_KEY_PRINT KEY_PRINT
#define NI_KEY_HP KEY_HP
#define NI_KEY_CAMERA KEY_CAMERA
#define NI_KEY_SOUND KEY_SOUND
#define NI_KEY_QUESTION KEY_QUESTION
#define NI_KEY_EMAIL KEY_EMAIL
#define NI_KEY_CHAT KEY_CHAT
#define NI_KEY_SEARCH KEY_SEARCH
#define NI_KEY_CONNECT KEY_CONNECT
#define NI_KEY_FINANCE KEY_FINANCE
#define NI_KEY_SPORT KEY_SPORT
#define NI_KEY_SHOP KEY_SHOP
#define NI_KEY_ALTERASE KEY_ALTERASE
#define NI_KEY_CANCEL KEY_CANCEL
#define NI_KEY_BRIGHTNESSDOWN KEY_BRIGHTNESSDOWN
#define NI_KEY_BRIGHTNESSUP KEY_BRIGHTNESSUP
#define NI_KEY_MEDIA KEY_MEDIA
#define NI_KEY_SWITCHVIDEOMODE KEY_SWITCHVIDEOMODE
#define NI_KEY_KBDILLUMTOGGLE KEY_KBDILLUMTOGGLE
#define NI_KEY_KBDILLUMDOWN KEY_KBDILLUMDOWN
#define NI_KEY_KBDILLUMUP KEY_KBDILLUMUP
#define NI_KEY_SEND KEY_SEND
#define NI_KEY_REPLY KEY_REPLY
#define NI_KEY_FORWARDMAIL KEY_FORWARDMAIL
#define NI_KEY_SAVE KEY_SAVE
#define NI_KEY_DOCUMENTS KEY_DOCUMENTS
#define NI_KEY_BATTERY KEY_BATTERY
#define NI_KEY_BLUETOOTH KEY_BLUETOOTH
#define NI_KEY_WLAN KEY_WLAN
#define NI_KEY_UWB KEY_UWB
#define NI_KEY_UNKNOWN KEY_UNKNOWN
#define NI_KEY_VIDEO_NEXT KEY_VIDEO_NEXT
#define NI_KEY_VIDEO_PREV KEY_VIDEO_PREV
#define NI_KEY_BRIGHTNESS_CYCLE KEY_BRIGHTNESS_CYCLE
#define NI_KEY_BRIGHTNESS_AUTO KEY_BRIGHTNESS_AUTO
#define NI_KEY_BRIGHTNESS_ZERO KEY_BRIGHTNESS_ZERO
#define NI_KEY_DISPLAY_OFF KEY_DISPLAY_OFF
#define NI_KEY_WWAN KEY_WWAN
#define NI_KEY_WIMAX KEY_WIMAX
#define NI_KEY_RFKILL KEY_RFKILL
#define NI_KEY_MICMUTE KEY_MICMUTE
#define NI_BTN_MISC BTN_MISC
#define NI_BTN_0 BTN_0
#define NI_BTN_1 BTN_1
#define NI_BTN_2 BTN_2
#define NI_BTN_3 BTN_3
#define NI_BTN_4 BTN_4
#define NI_BTN_5 BTN_5
#define NI_BTN_6 BTN_6
#define NI_BTN_7 BTN_7
#define NI_BTN_8 BTN_8
#define NI_BTN_9 BTN_9
#define NI_BTN_MOUSE BTN_MOUSE
#define NI_BTN_LEFT BTN_LEFT
#define NI_BTN_RIGHT BTN_RIGHT
#define NI_BTN_MIDDLE BTN_MIDDLE
#define NI_BTN_SIDE BTN_SIDE
#define NI_BTN_EXTRA BTN_EXTRA
#define NI_BTN_FORWARD BTN_FORWARD
#define NI_BTN_BACK BTN_BACK
#define NI_BTN_TASK BTN_TASK
#define NI_BTN_JOYSTICK BTN_JOYSTICK
#define NI_BTN_TRIGGER BTN_TRIGGER
#define NI_BTN_THUMB BTN_THUMB
#define NI_BTN_THUMB2 BTN_THUMB2
#define NI_BTN_TOP BTN_TOP
#define NI_BTN_TOP2 BTN_TOP2
#define NI_BTN_PINKIE BTN_PINKIE
#define NI_BTN_BASE BTN_BASE
#define NI_BTN_BASE2 BTN_BASE2
#define NI_BTN_BASE3 BTN_BASE3
#define NI_BTN_BASE4 BTN_BASE4
#define NI_BTN_BASE5 BTN_BASE5
#define NI_BTN_BASE6 BTN_BASE6
#define NI_BTN_DEAD BTN_DEAD
#define NI_BTN_GAMEPAD BTN_GAMEPAD
#define NI_BTN_SOUTH BTN_SOUTH
#define NI_BTN_A BTN_A
#define NI_BTN_EAST BTN_EAST
#define NI_BTN_B BTN_B
#define NI_BTN_C BTN_C
#define NI_BTN_NORTH BTN_NORTH
#define NI_BTN_X BTN_X
#define NI_BTN_WEST BTN_WEST
#define NI_BTN_Y BTN_Y
#define NI_BTN_Z BTN_Z
#define NI_BTN_TL BTN_TL
#define NI_BTN_TR BTN_TR
#define NI_BTN_TL2 BTN_TL2
#define NI_BTN_TR2 BTN_TR2
#define NI_BTN_SELECT BTN_SELECT
#define NI_BTN_START BTN_START
#define NI_BTN_MODE BTN_MODE
#define NI_BTN_THUMBL BTN_THUMBL
#define NI_BTN_THUMBR BTN_THUMBR
#define NI_BTN_DIGI BTN_DIGI
#define NI_BTN_TOOL_PEN BTN_TOOL_PEN
#define NI_BTN_TOOL_RUBBER BTN_TOOL_RUBBER
#define NI_BTN_TOOL_BRUSH BTN_TOOL_BRUSH
#define NI_BTN_TOOL_PENCIL BTN_TOOL_PENCIL
#define NI_BTN_TOOL_AIRBRUSH BTN_TOOL_AIRBRUSH
#define NI_BTN_TOOL_FINGER BTN_TOOL_FINGER
#define NI_BTN_TOOL_MOUSE BTN_TOOL_MOUSE
#define NI_BTN_TOOL_LENS BTN_TOOL_LENS
#define NI_BTN_TOOL_QUINTTAP BTN_TOOL_QUINTTAP
#define NI_BTN_STYLUS3 BTN_STYLUS3
#define NI_BTN_TOUCH BTN_TOUCH
#define NI_BTN_STYLUS BTN_STYLUS
#define NI_BTN_STYLUS2 BTN_STYLUS2
#define NI_BTN_TOOL_DOUBLETAP BTN_TOOL_DOUBLETAP
#define NI_BTN_TOOL_TRIPLETAP BTN_TOOL_TRIPLETAP
#define NI_BTN_TOOL_QUADTAP BTN_TOOL_QUADTAP
#define NI_BTN_WHEEL BTN_WHEEL
#define NI_BTN_GEAR_DOWN BTN_GEAR_DOWN
#define NI_BTN_GEAR_UP BTN_GEAR_UP
#define NI_KEY_OK KEY_OK
#define NI_KEY_SELECT KEY_SELECT
#define NI_KEY_GOTO KEY_GOTO
#define NI_KEY_CLEAR KEY_CLEAR
#define NI_KEY_POWER2 KEY_POWER2
#define NI_KEY_OPTION KEY_OPTION
#define NI_KEY_INFO KEY_INFO
#define NI_KEY_TIME KEY_TIME
#define NI_KEY_VENDOR KEY_VENDOR
#define NI_KEY_ARCHIVE KEY_ARCHIVE
#define NI_KEY_PROGRAM KEY_PROGRAM
#define NI_KEY_CHANNEL KEY_CHANNEL
#define NI_KEY_FAVORITES KEY_FAVORITES
#define NI_KEY_EPG KEY_EPG
#define NI_KEY_PVR KEY_PVR
#define NI_KEY_MHP KEY_MHP
#define NI_KEY_LANGUAGE KEY_LANGUAGE
#define NI_KEY_TITLE KEY_TITLE
#define NI_KEY_SUBTITLE KEY_SUBTITLE
#define NI_KEY_ANGLE KEY_ANGLE
#define NI_KEY_FULL_SCREEN KEY_FULL_SCREEN
#define NI_KEY_ZOOM KEY_ZOOM
#define NI_KEY_MODE KEY_MODE
#define NI_KEY_KEYBOARD KEY_KEYBOARD
#define NI_KEY_ASPECT_RATIO KEY_ASPECT_RATIO
#define NI_KEY_SCREEN KEY_SCREEN
#define NI_KEY_PC KEY_PC
#define NI_KEY_TV KEY_TV
#define NI_KEY_TV2 KEY_TV2
#define NI_KEY_VCR KEY_VCR
#define NI_KEY_VCR2 KEY_VCR2
#define NI_KEY_SAT KEY_SAT
#define NI_KEY_SAT2 KEY_SAT2
#define NI_KEY_CD KEY_CD
#define NI_KEY_TAPE KEY_TAPE
#define NI_KEY_RADIO KEY_RADIO
#define NI_KEY_TUNER KEY_TUNER
#define NI_KEY_PLAYER KEY_PLAYER
#define NI_KEY_TEXT KEY_TEXT
#define NI_KEY_DVD KEY_DVD
#define NI_KEY_AUX KEY_AUX
#define NI_KEY_MP3 KEY_MP3
#define NI_KEY_AUDIO KEY_AUDIO
#define NI_KEY_VIDEO KEY_VIDEO
#define NI_KEY_DIRECTORY KEY_DIRECTORY
#define NI_KEY_LIST KEY_LIST
#define NI_KEY_MEMO KEY_MEMO
#define NI_KEY_CALENDAR KEY_CALENDAR
#define NI_KEY_RED KEY_RED
#define NI_KEY_GREEN KEY_GREEN
#define NI_KEY_YELLOW KEY_YELLOW
#define NI_KEY_BLUE KEY_BLUE
#define NI_KEY_CHANNELUP KEY_CHANNELUP
#define NI_KEY_CHANNELDOWN KEY_CHANNELDOWN
#define NI_KEY_FIRST KEY_FIRST
#define NI_KEY_LAST KEY_LAST
#define NI_KEY_AB KEY_AB
#define NI_KEY_NEXT KEY_NEXT
#define NI_KEY_RESTART KEY_RESTART
#define NI_KEY_SLOW KEY_SLOW
#define NI_KEY_SHUFFLE KEY_SHUFFLE
#define NI_KEY_BREAK KEY_BREAK
#define NI_KEY_PREVIOUS KEY_PREVIOUS
#define NI_KEY_DIGITS KEY_DIGITS
#define NI_KEY_TEEN KEY_TEEN
#define NI_KEY_TWEN KEY_TWEN
#define NI_KEY_VIDEOPHONE KEY_VIDEOPHONE
#define NI_KEY_GAMES KEY_GAMES
#define NI_KEY_ZOOMIN KEY_ZOOMIN
#define NI_KEY_ZOOMOUT KEY_ZOOMOUT
#define NI_KEY_ZOOMRESET KEY_ZOOMRESET
#define NI_KEY_WORDPROCESSOR KEY_WORDPROCESSOR
#define NI_KEY_EDITOR KEY_EDITOR
#define NI_KEY_SPREADSHEET KEY_SPREADSHEET
#define NI_KEY_GRAPHICSEDITOR KEY_GRAPHICSEDITOR
#define NI_KEY_PRESENTATION KEY_PRESENTATION
#define NI_KEY_DATABASE KEY_DATABASE
#define NI_KEY_NEWS KEY_NEWS
#define NI_KEY_VOICEMAIL KEY_VOICEMAIL
#define NI_KEY_ADDRESSBOOK KEY_ADDRESSBOOK
#define NI_KEY_MESSENGER KEY_MESSENGER
#define NI_KEY_DISPLAYTOGGLE KEY_DISPLAYTOGGLE
#define NI_KEY_BRIGHTNESS_TOGGLE KEY_BRIGHTNESS_TOGGLE
#define NI_KEY_SPELLCHECK KEY_SPELLCHECK
#define NI_KEY_LOGOFF KEY_LOGOFF
#define NI_KEY_DOLLAR KEY_DOLLAR
#define NI_KEY_EURO KEY_EURO
#define NI_KEY_FRAMEBACK KEY_FRAMEBACK
#define NI_KEY_FRAMEFORWARD KEY_FRAMEFORWARD
#define NI_KEY_CONTEXT_MENU KEY_CONTEXT_MENU
#define NI_KEY_MEDIA_REPEAT KEY_MEDIA_REPEAT
#define NI_KEY_10CHANNELSUP KEY_10CHANNELSUP
#define NI_KEY_10CHANNELSDOWN KEY_10CHANNELSDOWN
#define NI_KEY_IMAGES KEY_IMAGES
#define NI_KEY_NOTIFICATION_CENTER KEY_NOTIFICATION_CENTER
#define NI_KEY_PICKUP_PHONE KEY_PICKUP_PHONE
#define NI_KEY_HANGUP_PHONE KEY_HANGUP_PHONE
#define NI_KEY_LINK_PHONE KEY_LINK_PHONE
#define NI_KEY_DEL_EOL KEY_DEL_EOL
#define NI_KEY_DEL_EOS KEY_DEL_EOS
#define NI_KEY_INS_LINE KEY_INS_LINE
#define NI_KEY_DEL_LINE KEY_DEL_LINE
#define NI_KEY_FN KEY_FN
#define NI_KEY_FN_ESC KEY_FN_ESC
#define NI_KEY_FN_F1 KEY_FN_F1
#define NI_KEY_FN_F2 KEY_FN_F2
#define NI_KEY_FN_F3 KEY_FN_F3
#define NI_KEY_FN_F4 KEY_FN_F4
#define NI_KEY_FN_F5 KEY_FN_F5
#define NI_KEY_FN_F6 KEY_FN_F6
#define NI_KEY_FN_F7 KEY_FN_F7
#define NI_KEY_FN_F8 KEY_FN_F8
#define NI_KEY_FN_F9 KEY_FN_F9
#define NI_KEY_FN_F10 KEY_FN_F10
#define NI_KEY_FN_F11 KEY_FN_F11
#define NI_KEY_FN_F12 KEY_FN_F12
#define NI_KEY_FN_1 KEY_FN_1
#define NI_KEY_FN_2 KEY_FN_2
#define NI_KEY_FN_D KEY_FN_D
#define NI_KEY_FN_E KEY_FN_E
#define NI_KEY_FN_F KEY_FN_F
#define NI_KEY_FN_S KEY_FN_S
#define NI_KEY_FN_B KEY_FN_B
#define NI_KEY_FN_RIGHT_SHIFT KEY_FN_RIGHT_SHIFT
#define NI_KEY_BRL_DOT1 KEY_BRL_DOT1
#define NI_KEY_BRL_DOT2 KEY_BRL_DOT2
#define NI_KEY_BRL_DOT3 KEY_BRL_DOT3
#define NI_KEY_BRL_DOT4 KEY_BRL_DOT4
#define NI_KEY_BRL_DOT5 KEY_BRL_DOT5
#define NI_KEY_BRL_DOT6 KEY_BRL_DOT6
#define NI_KEY_BRL_DOT7 KEY_BRL_DOT7
#define NI_KEY_BRL_DOT8 KEY_BRL_DOT8
#define NI_KEY_BRL_DOT9 KEY_BRL_DOT9
#define NI_KEY_BRL_DOT10 KEY_BRL_DOT10
#define NI_KEY_NUMERIC_0 KEY_NUMERIC_0
#define NI_KEY_NUMERIC_1 KEY_NUMERIC_1
#define NI_KEY_NUMERIC_2 KEY_NUMERIC_2
#define NI_KEY_NUMERIC_3 KEY_NUMERIC_3
#define NI_KEY_NUMERIC_4 KEY_NUMERIC_4
#define NI_KEY_NUMERIC_5 KEY_NUMERIC_5
#define NI_KEY_NUMERIC_6 KEY_NUMERIC_6
#define NI_KEY_NUMERIC_7 KEY_NUMERIC_7
#define NI_KEY_NUMERIC_8 KEY_NUMERIC_8
#define NI_KEY_NUMERIC_9 KEY_NUMERIC_9
#define NI_KEY_NUMERIC_STAR KEY_NUMERIC_STAR
#define NI_KEY_NUMERIC_POUND KEY_NUMERIC_POUND
#define NI_KEY_NUMERIC_A KEY_NUMERIC_A
#define NI_KEY_NUMERIC_B KEY_NUMERIC_B
#define NI_KEY_NUMERIC_C KEY_NUMERIC_C
#define NI_KEY_NUMERIC_D KEY_NUMERIC_D
#define NI_KEY_CAMERA_FOCUS KEY_CAMERA_FOCUS
#define NI_KEY_WPS_BUTTON KEY_WPS_BUTTON
#define NI_KEY_TOUCHPAD_TOGGLE KEY_TOUCHPAD_TOGGLE
#define NI_KEY_TOUCHPAD_ON KEY_TOUCHPAD_ON
#define NI_KEY_TOUCHPAD_OFF KEY_TOUCHPAD_OFF
#define NI_KEY_CAMERA_ZOOMIN KEY_CAMERA_ZOOMIN
#define NI_KEY_CAMERA_ZOOMOUT KEY_CAMERA_ZOOMOUT
#define NI_KEY_CAMERA_UP KEY_CAMERA_UP
#define NI_KEY_CAMERA_DOWN KEY_CAMERA_DOWN
#define NI_KEY_CAMERA_LEFT KEY_CAMERA_LEFT
#define NI_KEY_CAMERA_RIGHT KEY_CAMERA_RIGHT
#define NI_KEY_ATTENDANT_ON KEY_ATTENDANT_ON
#define NI_KEY_ATTENDANT_OFF KEY_ATTENDANT_OFF
#define NI_KEY_ATTENDANT_TOGGLE KEY_ATTENDANT_TOGGLE
#define NI_KEY_LIGHTS_TOGGLE KEY_LIGHTS_TOGGLE
#define NI_BTN_DPAD_UP BTN_DPAD_UP
#define NI_BTN_DPAD_DOWN BTN_DPAD_DOWN
#define NI_BTN_DPAD_LEFT BTN_DPAD_LEFT
#define NI_BTN_DPAD_RIGHT BTN_DPAD_RIGHT
#define NI_KEY_ALS_TOGGLE KEY_ALS_TOGGLE
#define NI_KEY_ROTATE_LOCK_TOGGLE KEY_ROTATE_LOCK_TOGGLE
#define NI_KEY_REFRESH_RATE_TOGGLE KEY_REFRESH_RATE_TOGGLE
#define NI_KEY_BUTTONCONFIG KEY_BUTTONCONFIG
#define NI_KEY_TASKMANAGER KEY_TASKMANAGER
#define NI_KEY_JOURNAL KEY_JOURNAL
#define NI_KEY_CONTROLPANEL KEY_CONTROLPANEL
#define NI_KEY_APPSELECT KEY_APPSELECT
#define NI_KEY_SCREENSAVER KEY_SCREENSAVER
#define NI_KEY_VOICECOMMAND KEY_VOICECOMMAND
#define NI_KEY_ASSISTANT KEY_ASSISTANT
#define NI_KEY_KBD_LAYOUT_NEXT KEY_KBD_LAYOUT_NEXT
#define NI_KEY_EMOJI_PICKER KEY_EMOJI_PICKER
#define NI_KEY_DICTATE KEY_DICTATE
#define NI_KEY_CAMERA_ACCESS_ENABLE KEY_CAMERA_ACCESS_ENABLE
#define NI_KEY_CAMERA_ACCESS_DISABLE KEY_CAMERA_ACCESS_DISABLE
#define NI_KEY_CAMERA_ACCESS_TOGGLE KEY_CAMERA_ACCESS_TOGGLE
#define NI_KEY_ACCESSIBILITY KEY_ACCESSIBILITY
#define NI_KEY_DO_NOT_DISTURB KEY_DO_NOT_DISTURB
#define NI_KEY_BRIGHTNESS_MIN KEY_BRIGHTNESS_MIN
#define NI_KEY_BRIGHTNESS_MAX KEY_BRIGHTNESS_MAX
#define NI_KEY_KBDINPUTASSIST_PREV KEY_KBDINPUTASSIST_PREV
#define NI_KEY_KBDINPUTASSIST_NEXT KEY_KBDINPUTASSIST_NEXT
#define NI_KEY_KBDINPUTASSIST_PREVGROUP KEY_KBDINPUTASSIST_PREVGROUP
#define NI_KEY_KBDINPUTASSIST_NEXTGROUP KEY_KBDINPUTASSIST_NEXTGROUP
#define NI_KEY_KBDINPUTASSIST_ACCEPT KEY_KBDINPUTASSIST_ACCEPT
#define NI_KEY_KBDINPUTASSIST_CANCEL KEY_KBDINPUTASSIST_CANCEL
#define NI_KEY_RIGHT_UP KEY_RIGHT_UP
#define NI_KEY_RIGHT_DOWN KEY_RIGHT_DOWN
#define NI_KEY_LEFT_UP KEY_LEFT_UP
#define NI_KEY_LEFT_DOWN KEY_LEFT_DOWN
#define NI_KEY_ROOT_MENU KEY_ROOT_MENU
#define NI_KEY_MEDIA_TOP_MENU KEY_MEDIA_TOP_MENU
#define NI_KEY_NUMERIC_11 KEY_NUMERIC_11
#define NI_KEY_NUMERIC_12 KEY_NUMERIC_12
#define NI_KEY_AUDIO_DESC KEY_AUDIO_DESC
#define NI_KEY_3D_MODE KEY_3D_MODE
#define NI_KEY_NEXT_FAVORITE KEY_NEXT_FAVORITE
#define NI_KEY_STOP_RECORD KEY_STOP_RECORD
#define NI_KEY_PAUSE_RECORD KEY_PAUSE_RECORD
#define NI_KEY_VOD KEY_VOD
#define NI_KEY_UNMUTE KEY_UNMUTE
#define NI_KEY_FASTREVERSE KEY_FASTREVERSE
#define NI_KEY_SLOWREVERSE KEY_SLOWREVERSE
#define NI_KEY_DATA KEY_DATA
#define NI_KEY_ONSCREEN_KEYBOARD KEY_ONSCREEN_KEYBOARD
#define NI_KEY_PRIVACY_SCREEN_TOGGLE KEY_PRIVACY_SCREEN_TOGGLE
#define NI_KEY_SELECTIVE_SCREENSHOT KEY_SELECTIVE_SCREENSHOT
#define NI_KEY_NEXT_ELEMENT KEY_NEXT_ELEMENT
#define NI_KEY_PREVIOUS_ELEMENT KEY_PREVIOUS_ELEMENT
#define NI_KEY_AUTOPILOT_ENGAGE_TOGGLE KEY_AUTOPILOT_ENGAGE_TOGGLE
#define NI_KEY_MARK_WAYPOINT KEY_MARK_WAYPOINT
#define NI_KEY_SOS KEY_SOS
#define NI_KEY_NAV_CHART KEY_NAV_CHART
#define NI_KEY_FISHING_CHART KEY_FISHING_CHART
#define NI_KEY_SINGLE_RANGE_RADAR KEY_SINGLE_RANGE_RADAR
#define NI_KEY_DUAL_RANGE_RADAR KEY_DUAL_RANGE_RADAR
#define NI_KEY_RADAR_OVERLAY KEY_RADAR_OVERLAY
#define NI_KEY_TRADITIONAL_SONAR KEY_TRADITIONAL_SONAR
#define NI_KEY_CLEARVU_SONAR KEY_CLEARVU_SONAR
#define NI_KEY_SIDEVU_SONAR KEY_SIDEVU_SONAR
#define NI_KEY_NAV_INFO KEY_NAV_INFO
#define NI_KEY_BRIGHTNESS_MENU KEY_BRIGHTNESS_MENU
#define NI_KEY_MACRO1 KEY_MACRO1
#define NI_KEY_MACRO2 KEY_MACRO2
#define NI_KEY_MACRO3 KEY_MACRO3
#define NI_KEY_MACRO4 KEY_MACRO4
#define NI_KEY_MACRO5 KEY_MACRO5
#define NI_KEY_MACRO6 KEY_MACRO6
#define NI_KEY_MACRO7 KEY_MACRO7
#define NI_KEY_MACRO8 KEY_MACRO8
#define NI_KEY_MACRO9 KEY_MACRO9
#define NI_KEY_MACRO10 KEY_MACRO10
#define NI_KEY_MACRO11 KEY_MACRO11
#define NI_KEY_MACRO12 KEY_MACRO12
#define NI_KEY_MACRO13 KEY_MACRO13
#define NI_KEY_MACRO14 KEY_MACRO14
#define NI_KEY_MACRO15 KEY_MACRO15
#define NI_KEY_MACRO16 KEY_MACRO16
#define NI_KEY_MACRO17 KEY_MACRO17
#define NI_KEY_MACRO18 KEY_MACRO18
#define NI_KEY_MACRO19 KEY_MACRO19
#define NI_KEY_MACRO20 KEY_MACRO20
#define NI_KEY_MACRO21 KEY_MACRO21
#define NI_KEY_MACRO22 KEY_MACRO22
#define NI_KEY_MACRO23 KEY_MACRO23
#define NI_KEY_MACRO24 KEY_MACRO24
#define NI_KEY_MACRO25 KEY_MACRO25
#define NI_KEY_MACRO26 KEY_MACRO26
#define NI_KEY_MACRO27 KEY_MACRO27
#define NI_KEY_MACRO28 KEY_MACRO28
#define NI_KEY_MACRO29 KEY_MACRO29
#define NI_KEY_MACRO30 KEY_MACRO30
#define NI_KEY_MACRO_RECORD_START KEY_MACRO_RECORD_START
#define NI_KEY_MACRO_RECORD_STOP KEY_MACRO_RECORD_STOP
#define NI_KEY_MACRO_PRESET_CYCLE KEY_MACRO_PRESET_CYCLE
#define NI_KEY_MACRO_PRESET1 KEY_MACRO_PRESET1
#define NI_KEY_MACRO_PRESET2 KEY_MACRO_PRESET2
#define NI_KEY_MACRO_PRESET3 KEY_MACRO_PRESET3
#define NI_KEY_KBD_LCD_MENU1 KEY_KBD_LCD_MENU1
#define NI_KEY_KBD_LCD_MENU2 KEY_KBD_LCD_MENU2
#define NI_KEY_KBD_LCD_MENU3 KEY_KBD_LCD_MENU3
#define NI_KEY_KBD_LCD_MENU4 KEY_KBD_LCD_MENU4
#define NI_KEY_KBD_LCD_MENU5 KEY_KBD_LCD_MENU5
#define NI_BTN_TRIGGER_HAPPY BTN_TRIGGER_HAPPY
#define NI_BTN_TRIGGER_HAPPY1 BTN_TRIGGER_HAPPY1
#define NI_BTN_TRIGGER_HAPPY2 BTN_TRIGGER_HAPPY2
#define NI_BTN_TRIGGER_HAPPY3 BTN_TRIGGER_HAPPY3
#define NI_BTN_TRIGGER_HAPPY4 BTN_TRIGGER_HAPPY4
#define NI_BTN_TRIGGER_HAPPY5 BTN_TRIGGER_HAPPY5
#define NI_BTN_TRIGGER_HAPPY6 BTN_TRIGGER_HAPPY6
#define NI_BTN_TRIGGER_HAPPY7 BTN_TRIGGER_HAPPY7
#define NI_BTN_TRIGGER_HAPPY8 BTN_TRIGGER_HAPPY8
#define NI_BTN_TRIGGER_HAPPY9 BTN_TRIGGER_HAPPY9
#define NI_BTN_TRIGGER_HAPPY10 BTN_TRIGGER_HAPPY10
#define NI_BTN_TRIGGER_HAPPY11 BTN_TRIGGER_HAPPY11
#define NI_BTN_TRIGGER_HAPPY12 BTN_TRIGGER_HAPPY12
#define NI_BTN_TRIGGER_HAPPY13 BTN_TRIGGER_HAPPY13
#define NI_BTN_TRIGGER_HAPPY14 BTN_TRIGGER_HAPPY14
#define NI_BTN_TRIGGER_HAPPY15 BTN_TRIGGER_HAPPY15
#define NI_BTN_TRIGGER_HAPPY16 BTN_TRIGGER_HAPPY16
#define NI_BTN_TRIGGER_HAPPY17 BTN_TRIGGER_HAPPY17
#define NI_BTN_TRIGGER_HAPPY18 BTN_TRIGGER_HAPPY18
#define NI_BTN_TRIGGER_HAPPY19 BTN_TRIGGER_HAPPY19
#define NI_BTN_TRIGGER_HAPPY20 BTN_TRIGGER_HAPPY20
#define NI_BTN_TRIGGER_HAPPY21 BTN_TRIGGER_HAPPY21
#define NI_BTN_TRIGGER_HAPPY22 BTN_TRIGGER_HAPPY22
#define NI_BTN_TRIGGER_HAPPY23 BTN_TRIGGER_HAPPY23
#define NI_BTN_TRIGGER_HAPPY24 BTN_TRIGGER_HAPPY24
#define NI_BTN_TRIGGER_HAPPY25 BTN_TRIGGER_HAPPY25
#define NI_BTN_TRIGGER_HAPPY26 BTN_TRIGGER_HAPPY26
#define NI_BTN_TRIGGER_HAPPY27 BTN_TRIGGER_HAPPY27
#define NI_BTN_TRIGGER_HAPPY28 BTN_TRIGGER_HAPPY28
#define NI_BTN_TRIGGER_HAPPY29 BTN_TRIGGER_HAPPY29
#define NI_BTN_TRIGGER_HAPPY30 BTN_TRIGGER_HAPPY30
#define NI_BTN_TRIGGER_HAPPY31 BTN_TRIGGER_HAPPY31
#define NI_BTN_TRIGGER_HAPPY32 BTN_TRIGGER_HAPPY32
#define NI_BTN_TRIGGER_HAPPY33 BTN_TRIGGER_HAPPY33
#define NI_BTN_TRIGGER_HAPPY34 BTN_TRIGGER_HAPPY34
#define NI_BTN_TRIGGER_HAPPY35 BTN_TRIGGER_HAPPY35
#define NI_BTN_TRIGGER_HAPPY36 BTN_TRIGGER_HAPPY36
#define NI_BTN_TRIGGER_HAPPY37 BTN_TRIGGER_HAPPY37
#define NI_BTN_TRIGGER_HAPPY38 BTN_TRIGGER_HAPPY38
#define NI_BTN_TRIGGER_HAPPY39 BTN_TRIGGER_HAPPY39
#define NI_BTN_TRIGGER_HAPPY40 BTN_TRIGGER_HAPPY40
#define NI_KEY_MIN_INTERESTING KEY_MIN_INTERESTING
#define NI_KEY_MAX KEY_MAX
#define NI_KEY_CNT KEY_CNT
#define NI_REL_X REL_X
#define NI_REL_Y REL_Y
#define NI_REL_Z REL_Z
#define NI_REL_RX REL_RX
#define NI_REL_RY REL_RY
#define NI_REL_RZ REL_RZ
#define NI_REL_HWHEEL REL_HWHEEL
#define NI_REL_DIAL REL_DIAL
#define NI_REL_WHEEL REL_WHEEL
#define NI_REL_MISC REL_MISC
#define NI_REL_RESERVED REL_RESERVED
#define NI_REL_WHEEL_HI_RES REL_WHEEL_HI_RES
#define NI_REL_HWHEEL_HI_RES REL_HWHEEL_HI_RES
#define NI_REL_MAX REL_MAX
#define NI_REL_CNT REL_CNT
#define NI_ABS_X ABS_X
#define NI_ABS_Y ABS_Y
#define NI_ABS_Z ABS_Z
#define NI_ABS_RX ABS_RX
#define NI_ABS_RY ABS_RY
#define NI_ABS_RZ ABS_RZ
#define NI_ABS_THROTTLE ABS_THROTTLE
#define NI_ABS_RUDDER ABS_RUDDER
#define NI_ABS_WHEEL ABS_WHEEL
#define NI_ABS_GAS ABS_GAS
#define NI_ABS_BRAKE ABS_BRAKE
#define NI_ABS_HAT0X ABS_HAT0X
#define NI_ABS_HAT0Y ABS_HAT0Y
#define NI_ABS_HAT1X ABS_HAT1X
#define NI_ABS_HAT1Y ABS_HAT1Y
#define NI_ABS_HAT2X ABS_HAT2X
#define NI_ABS_HAT2Y ABS_HAT2Y
#define NI_ABS_HAT3X ABS_HAT3X
#define NI_ABS_HAT3Y ABS_HAT3Y
#define NI_ABS_PRESSURE ABS_PRESSURE
#define NI_ABS_DISTANCE ABS_DISTANCE
#define NI_ABS_TILT_X ABS_TILT_X
#define NI_ABS_TILT_Y ABS_TILT_Y
#define NI_ABS_TOOL_WIDTH ABS_TOOL_WIDTH
#define NI_ABS_VOLUME ABS_VOLUME
#define NI_ABS_PROFILE ABS_PROFILE
#define NI_ABS_MISC ABS_MISC
#define NI_ABS_RESERVED ABS_RESERVED
#define NI_ABS_MT_SLOT ABS_MT_SLOT
#define NI_ABS_MT_TOUCH_MAJOR ABS_MT_TOUCH_MAJOR
#define NI_ABS_MT_TOUCH_MINOR ABS_MT_TOUCH_MINOR
#define NI_ABS_MT_WIDTH_MAJOR ABS_MT_WIDTH_MAJOR
#define NI_ABS_MT_WIDTH_MINOR ABS_MT_WIDTH_MINOR
#define NI_ABS_MT_ORIENTATION ABS_MT_ORIENTATION
#define NI_ABS_MT_POSITION_X ABS_MT_POSITION_X
#define NI_ABS_MT_POSITION_Y ABS_MT_POSITION_Y
#define NI_ABS_MT_TOOL_TYPE ABS_MT_TOOL_TYPE
#define NI_ABS_MT_BLOB_ID ABS_MT_BLOB_ID
#define NI_ABS_MT_TRACKING_ID ABS_MT_TRACKING_ID
#define NI_ABS_MT_PRESSURE ABS_MT_PRESSURE
#define NI_ABS_MT_DISTANCE ABS_MT_DISTANCE
#define NI_ABS_MT_TOOL_X ABS_MT_TOOL_X
#define NI_ABS_MT_TOOL_Y ABS_MT_TOOL_Y
#define NI_ABS_MAX ABS_MAX
#define NI_ABS_CNT ABS_CNT
#define NI_SW_LID SW_LID
#define NI_SW_TABLET_MODE SW_TABLET_MODE
#define NI_SW_HEADPHONE_INSERT SW_HEADPHONE_INSERT
#define NI_SW_RFKILL_ALL SW_RFKILL_ALL
#define NI_SW_RADIO SW_RADIO
#define NI_SW_MICROPHONE_INSERT SW_MICROPHONE_INSERT
#define NI_SW_DOCK SW_DOCK
#define NI_SW_LINEOUT_INSERT SW_LINEOUT_INSERT
#define NI_SW_JACK_PHYSICAL_INSERT SW_JACK_PHYSICAL_INSERT
#define NI_SW_VIDEOOUT_INSERT SW_VIDEOOUT_INSERT
#define NI_SW_CAMERA_LENS_COVER SW_CAMERA_LENS_COVER
#define NI_SW_KEYPAD_SLIDE SW_KEYPAD_SLIDE
#define NI_SW_FRONT_PROXIMITY SW_FRONT_PROXIMITY
#define NI_SW_ROTATE_LOCK SW_ROTATE_LOCK
#define NI_SW_LINEIN_INSERT SW_LINEIN_INSERT
#define NI_SW_MUTE_DEVICE SW_MUTE_DEVICE
#define NI_SW_PEN_INSERTED SW_PEN_INSERTED
#define NI_SW_MACHINE_COVER SW_MACHINE_COVER
#define NI_SW_USB_INSERT SW_USB_INSERT
#define NI_SW_MAX SW_MAX
#define NI_SW_CNT SW_CNT
#define NI_MSC_SERIAL MSC_SERIAL
#define NI_MSC_PULSELED MSC_PULSELED
#define NI_MSC_GESTURE MSC_GESTURE
#define NI_MSC_RAW MSC_RAW
#define NI_MSC_SCAN MSC_SCAN
#define NI_MSC_TIMESTAMP MSC_TIMESTAMP
#define NI_MSC_MAX MSC_MAX
#define NI_MSC_CNT MSC_CNT
#define NI_LED_NUML LED_NUML
#define NI_LED_CAPSL LED_CAPSL
#define NI_LED_SCROLLL LED_SCROLLL
#define NI_LED_COMPOSE LED_COMPOSE
#define NI_LED_KANA LED_KANA
#define NI_LED_SLEEP LED_SLEEP
#define NI_LED_SUSPEND LED_SUSPEND
#define NI_LED_MUTE LED_MUTE
#define NI_LED_MISC LED_MISC
#define NI_LED_MAIL LED_MAIL
#define NI_LED_CHARGING LED_CHARGING
#define NI_LED_MAX LED_MAX
#define NI_LED_CNT LED_CNT
#define NI_REP_DELAY REP_DELAY
#define NI_REP_PERIOD REP_PERIOD
#define NI_REP_MAX REP_MAX
#define NI_REP_CNT REP_CNT
#define NI_SND_CLICK SND_CLICK
#define NI_SND_BELL SND_BELL
#define NI_SND_TONE SND_TONE
#define NI_SND_MAX SND_MAX
#define NI_SND_CNT SND_CNT
#else
   /* Non-Linux placeholders: stable values defined by this library */
#  define NI_EV_SYN   0x00
#  define NI_EV_KEY   0x01
#  define NI_EV_REL   0x02
#  define NI_EV_ABS   0x03
#  define NI_EV_MSC   0x04
#  define NI_KEY_A        0x1E
#  define NI_KEY_D        0x20
#  define NI_KEY_S        0x1F
#  define NI_KEY_W        0x11
#  define NI_KEY_Q        0x10
#  define NI_KEY_ESC      0x01
#  define NI_KEY_ENTER    0x1C
#  define NI_KEY_SPACE    0x39
#  define NI_KEY_LEFTCTRL 0x1D
#  define NI_KEY_RIGHTCTRL 0x11D
#  define NI_KEY_LEFTALT  0x38
#  define NI_KEY_RIGHTALT 0x138
#  define NI_KEY_F1       0x3B
#  define NI_KEY_F12      0x58
#  define NI_KEY_UP       0xC8
#  define NI_KEY_DOWN     0xD0
#  define NI_KEY_LEFT     0xCB
#  define NI_KEY_RIGHT    0xCD
#  define NI_KEY_TAB      0x0F
#  define NI_KEY_BACKSPACE 0x0E
#  define NI_KEY_DELETE   0xD3
#  define NI_KEY_INSERT   0xD2
#  define NI_KEY_HOME     0xC7
#  define NI_KEY_END      0xCF
#  define NI_KEY_PAGEUP   0xC9
#  define NI_KEY_PAGEDOWN 0xD1
#  define NI_SYN_REPORT   0
#  define NI_MSC_SCAN     0
#  define NI_REL_X        0x00
#  define NI_REL_Y        0x01
#  define NI_REL_WHEEL    0x08
#  define NI_REL_HWHEEL   0x06
#  define NI_BTN_LEFT     0x110
#  define NI_BTN_RIGHT    0x111
#  define NI_BTN_MIDDLE   0x112
#  define NI_BTN_SIDE     0x113
#  define NI_BTN_EXTRA    0x114
#endif

/* Public event structure */
struct ni_event {
	int device_id;     /* stable ID assigned by library for the device */
	int type;          /* NI_EV_* (maps to platform native type) */
	int code;          /* NI_KEY_* (for EV_KEY) or platform native for other types */
	int value;         /* 1=down, 0=up, or axis delta/value */
	long long timestamp_ns; /* kernel/device-provided timestamp if available; otherwise CLOCK_MONOTONIC */
};

/* Device info for filtering */
struct ni_device_info {
    int id;                 /* library-assigned id (proposed) */
    char path[128];         /* /dev/input/eventX */
    unsigned short bustype; /* from EVIOCGID */
    unsigned short vendor;  /* from EVIOCGID */
    unsigned short product; /* from EVIOCGID */
    unsigned short version; /* from EVIOCGID */
    char name[256];         /* from EVIOCGNAME if available */
};

typedef int (*ni_device_filter)(const struct ni_device_info *info, void *user_data);

/* Set a device filter; only matching devices will be opened.
 * If called after ni_init, the library will rescan devices and close non-matching ones.
 * Returns 0 on success.
 */
int ni_set_device_filter(ni_device_filter filter, void *user_data);

/* Return number of currently opened devices that passed the filter */
int ni_device_count(void);

/* Zero-cost inline helpers (compile away) */
static inline int ni_is_key_event(const struct ni_event *ev) {
    return ev && ev->type == NI_EV_KEY;
}
static inline int ni_key_down(const struct ni_event *ev) {
    return ni_is_key_event(ev) && ev->value != 0;
}
static inline int ni_is_rel_event(const struct ni_event *ev) {
    return ev && ev->type == NI_EV_REL;
}
static inline int ni_is_mouse_button_code(int code) {
    return (code == NI_BTN_LEFT || code == NI_BTN_RIGHT || code == NI_BTN_MIDDLE || code == NI_BTN_SIDE || code == NI_BTN_EXTRA);
}
static inline int ni_button_down(const struct ni_event *ev) {
    return ev && ev->type == NI_EV_KEY && ni_is_mouse_button_code(ev->code) && ev->value != 0;
}

typedef void (*ni_callback)(const struct ni_event *ev, void *user_data);
typedef void (*ni_device_callback)(const struct ni_event *ev, const struct ni_device_info *device, void *user_data);

/* High-level key event produced by the optional xkb layer. Mirrors SDL-style input. */
struct ni_key_event {
    int device_id;              /* originating device */
    uint32_t keysym;            /* xkb keysym (XKB_KEY_*), 0 if none */
    char text[64];              /* UTF-8 text for this key press (if any), NUL-terminated */
    int down;                   /* 1 on key press, 0 on release */
    uint32_t mods;              /* bitmask of active modifiers (see NI_KMOD_*) */
    long long timestamp_ns;     /* timestamp of underlying kernel event */
};

enum {
    NI_KMOD_SHIFT = 1u << 0,
    NI_KMOD_CTRL  = 1u << 1,
    NI_KMOD_ALT   = 1u << 2,
    NI_KMOD_SUPER = 1u << 3,
};

typedef void (*ni_key_callback)(const struct ni_key_event *kev, void *user_data);

/* Device-specific callback registration flags */
#define NI_CB_FLAG_EXCLUSIVE    0x01  /* Only this callback for this device */
#define NI_CB_FLAG_HIGH_PRIORITY 0x02  /* Process before global callbacks */
#define NI_CB_FLAG_BATCH_EVENTS 0x04  /* Batch multiple events per callback */

/* Register a device-specific callback. Returns callback ID on success, -1 on error.
 * device_id: specific device ID, or -1 for all devices matching filter
 * cb: callback function
 * user_data: passed to callback
 * flags: combination of NI_CB_FLAG_*
 */
int ni_register_device_callback(int device_id, ni_device_callback cb, void *user_data, int flags);

/* Unregister a device-specific callback by ID */
int ni_unregister_device_callback(int callback_id);

/* Initialize library. flags reserved for future use, must be 0 for now. */
int
ni_init(int flags);

/* Enable or disable reading from /dev/input/mice (Linux only). When enabled,
 * a background reader parses PS/2 mouse packets and emits NI_EV_REL for
 * NI_REL_X/NI_REL_Y and NI_EV_KEY for NI_BTN_LEFT/RIGHT/MIDDLE via the same
 * callback/queue. Call before or after ni_init. Returns 0 on success, -1 on
 * unsupported platforms or on failure to start the reader. */
int
ni_enable_mice(int enabled);

/* Register a callback invoked from worker thread. flags reserved (0). */
int
ni_register_callback(ni_callback cb, void *user_data, int flags);

/* Optional xkb layer control (Linux/evdev-focused). When enabled, the library
 * will translate EV_KEY events to xkb keysyms and UTF-8 text and expose them
 * via a separate callback/queue API below. Defaults to disabled. Returns 0 on success.
 */
int ni_enable_xkb(int enabled);

/* Configure the xkb keymap using RMLVO names. Any argument may be NULL to use
 * the default. Call before ni_enable_xkb(1) or anytime to rebuild the keymap. */
int ni_set_xkb_names(const char *rules, const char *model, const char *layout,
                     const char *variant, const char *options);

/* Register a high-level key callback. Mutually independent from the low-level callback. */
int ni_register_key_callback(ni_key_callback cb, void *user_data, int flags);

/* Poll high-level key events. Returns count. */
int ni_poll_key_events(struct ni_key_event *evts, int max_events);

/* Poll queued events into evts (main-thread consumption). Returns count. */
int
ni_poll(struct ni_event *evts, int max_events);

/* Shutdown library and free resources. */
int
ni_shutdown(void);

#ifdef __cplusplus
}
#endif

#endif /* ASYNCINPUT_H */

